http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  music:
    host: localhost
    paths: ['/musics','/musics/*']
  employee:
    host: localhost
    paths: ['/testemp','/get/*','/list','/save2','/save']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  musicservices:
    url: 'http://localhost:8000'
  employeeservices:
    url: 'http://localhost:8989'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  employeepipeline:
    apiEndpoints:
      - employee
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: employeeservices 
              changeOrigin: true
  musicpipeline:
    apiEndpoints:
      - music
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: musicservices 
              changeOrigin: true

